services:

  db:
    image: mysql:8.0

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Alumnos
      MYSQL_USER: emiliano
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - "./mysql/:/var/lib/mysql"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      PMA_HOST: db
      PMA_USER: emiliano
      PMA_PASSWORD: 1234